import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    centered: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },
    list: {
      width: "100%",
      flex: 1,
    },
    container: {
      flex: 1,
    },
    contentContainer: {
      flex: 1,
      padding: 20,
      backgroundColor: "white",
    },
    bottomSheetHeader: {
      width: "100%",
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: "#E5E5E5",
      marginBottom: 20,
    },
    bottomSheetTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#006348",
      textAlign: "center",
    },
    orderSummary: {
      flex: 1,
      width: "100%",
    },
    mcontainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      backgroundColor: 'white',
      padding: 20,
      borderRadius: 15,
      width: '100%',
      maxWidth: 400,
      maxHeight: '80%',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    modalHeader: {
      alignItems: 'center',
      marginBottom: 20,
      paddingTop: 10,
    },
    successTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#006348',
      marginTop: 10,
      textAlign: 'center',
    },
    orderSummaryContainer: {
      marginVertical: 20,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: '#E5E5E5',
      paddingVertical: 15,
      maxHeight: '50%',
    },
    summaryTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 15,
      textAlign: 'right',
    },
    modalSummaryItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    modalSummaryItemLeft: {
      flex: 1,
      alignItems: 'flex-end',
    },
    modalSummaryItemName: {
      fontSize: 16,
      color: '#333',
      textAlign: 'right',
    },
    modalSummaryItemQuantity: {
      fontSize: 14,
      color: '#666',
      marginTop: 4,
    },
    modalSummaryItemPrice: {
      fontSize: 16,
      color: '#006348',
      marginRight: 10,
    },
    modalTotalContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 15,
      paddingTop: 15,
      borderTopWidth: 1,
      borderTopColor: '#E5E5E5',
    },
    modalTotalText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
    },
    modalTotalPrice: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#006348',
    },
    confirmationMessage: {
      fontSize: 16,
      color: '#666',
      textAlign: 'center',
      marginVertical: 20,
      lineHeight: 24,
    },
    modalButton: {
      backgroundColor: '#A37E2C',
      paddingVertical: 12,
      borderRadius: 30,
      alignItems: 'center',
    },
    modalButtonText: {
      color: 'white',
      fontSize: 18,
      fontWeight: 'bold',
    },
    quantity: {
      fontSize: 12,
      fontWeight: "bold",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderColor: "#006348",
      borderWidth: 0.5,
      borderRadius: 4,
    },
    emptyContainer: {
      flex: 1,
      height: 300,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyText: {
      marginTop: 10,
      fontSize: 16,
      textAlign: "center",
      color: "#006348",
    },
    item: {
      flexDirection: "row",
      alignItems: "center",
      padding: 10,
      borderRadius: 10,
      width: "100%",
    },
    image: {
      width: 70,
      height: 70,
      marginRight: 15,
      borderRadius: 10,
    },
    name: {
      fontSize: 16,
      fontWeight: "bold",
    },
    price: {
      color: "#006348",
      fontSize: 14,
      marginTop: 4,
    },
    quantityContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 16,
    },
    saveButtonContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 10,
      marginRight: 10,
    },
    saveButton: {
      backgroundColor: "#006348",
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "500",
    },
    saveButtonDisabled: {
      opacity: 0.7,
    },
    footerContainer: {
      padding: 12,
      margin: 12,
      borderRadius: 12,
      backgroundColor: "#80f",
    },
    footerText: {
      textAlign: "center",
      color: "white",
      fontWeight: "800",
    },
    quantityButton: {
      padding: 4,
    },
    deleteButton: {
      padding: 4,
    },
    totalItemPrice: {
      color: "#006348",
      fontSize: 12,
      marginTop: 2,
    },
    submitButton: {
      backgroundColor: "#A37E2C",
      paddingVertical: 10,
      paddingHorizontal: 30,
      borderRadius: 30,
      alignItems: "center",
      marginTop: 20,
      marginBottom: 50,
      width: "100%",
    },
    submitButtonText: {
      color: "white",
      fontSize: 18,
      fontWeight: "bold",
      textAlign: "center",
    },
    summaryItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#E5E5E5",
    },
    summaryItemLeft: {
      flex: 1,
      alignItems: "flex-end",
    },
    summaryItemName: {
      fontSize: 16,
      fontWeight: "500",
      color: "#333",
    },
    summaryItemQuantity: {
      fontSize: 14,
      color: "#666",
      marginTop: 4,
    },
    summaryItemPrice: {
      fontSize: 16,
      fontWeight: "500",
      color: "#006348",
      marginRight: 10,
    },
    totalContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 20,
      paddingTop: 20,
    },
    totalText: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
    },
    totalPrice: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#006348",
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#006348',
      marginBottom: 15,
      textAlign: 'center',
    },
    modalInput: {
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 8,
      padding: 10,
      marginBottom: 20,
    },
    modalButtonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    
  });
  
  export default styles;